default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  host: <%= ENV.fetch("DATABASE_HOST") { '127.0.0.1' } %>

development:
  <<: *default
  database: fullstack_example_development

test:
  <<: *default
  database: fullstack_example_test

staging:
  <<: *default
  database: fullstack_example_staging

production:
  <<: *default
  database: fullstack_example_production
